# Generated by Django 4.1.3 on 2022-12-03 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_weight', models.IntegerField(default=0)),
                ('dish_name', models.CharField(max_length=255)),
                ('dish_price', models.IntegerField(default=0)),
                ('dish_img', models.ImageField(blank=True, null=True, upload_to='items')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_display_name',
        ),
        migrations.RemoveField(
            model_name='type',
            name='type_display_name',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type'),
        ),
    ]
