# Generated by Django 4.1.3 on 2022-12-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_dish_dish_type_dish_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_price',
            field=models.FloatField(default=0.0),
        ),
    ]
