# Generated by Django 4.1.3 on 2022-12-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dish_dish_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dish_img',
            new_name='dish_image',
        ),
    ]
